create table _user(id bigint generated by default as identity primary key,
                   first_name varchar(30) not null,
                   last_name varchar(30) not null,
                   email varchar(50) not null unique,
                   age int check (age > 16) ,
                   is_active boolean,
                   username varchar not null
);

create table user_credential(
                                id int generated by default as identity primary key,
                                user_id bigint references _user(id) on delete cascade ,
                                password varchar,
                                pass_exp boolean,
                                pass_exp_date date,
                                update_at date,
                                temp_pass varchar
);

create table user_role (
                           id int generated by default as identity primary key,
                           role varchar not null,
                           user_id int references _user(id) on delete cascade ,
                           start_date date,
                           end_date date
);

create table user_bank_card_info(
                                    id int generated by default as identity primary key,
                                    card_number varchar(16) not null,
                                    exp_date date not null,
                                    is_active boolean,
                                    user_id int references _user(id) on delete cascade,
                                    cash double precision check ( cash >= 0 )
);

create table user_transaction_history(
                                         id int generated by default as identity primary key,
                                         user_id int references _user(id) on delete cascade ,
                                         transaction_status varchar,
                                         sum double precision,
                                         transaction_type varchar,
                                         comment varchar,
                                         card_num varchar
);

create table user_customer(
                              id int generated by default as identity primary key,
                              customer_name varchar(100) unique,
                              license_num varchar,
                              start_date date,
                              end_date date,
                              user_id int references _user(id) on delete cascade,
                              status varchar,
                              avg_rate double precision check ( avg_rate >= 0 )
);

create table price(
                      id int generated by default as identity primary key,
                      price int check ( price > 0 ),
                      is_sale boolean,
                      created_date date,
                      currency_type varchar
);

create table category(
                         id int generated by default as identity primary key,
                         category_name varchar not null
);

create table product(
                        id int generated by default as identity primary key,
                        category_id int references category(id) on delete cascade ,
                        price_id int references price(id) on delete cascade ,
                        customer_id int references user_customer(id) on delete cascade,
                        created_date date,
                        product_name varchar,
                        description text,
                        quantity int
);

create table orders (
                        id int generated by default as identity primary key,
                        created_date date,
                        delivery_date date,
                        buyer_id int references _user(id) on delete cascade ,
                        delivery_address date,
                        is_payed boolean,
                        transaction_id int references user_transaction_history(id) on delete cascade
);

create table order_details(
                              id int generated by default as identity primary key,
                              order_id int references orders(id) on delete cascade ,
                              product_id int references product(id) on delete cascade ,
                              seller_id int references user_customer(id) on delete cascade,
                              order_status varchar,
                              price double precision,
                              delivery_code varchar
);

create table customer_request(
                                 request_id int generated by default as identity primary key,
                                 executor_id int references _user(id) on delete cascade,
                                 customer_id int references _user(id) on delete cascade,
                                 customer_name varchar,
                                 license_num varchar
);

create table product_images(
                               id int generated by default as identity primary key,
                               product_id int references product(id) on delete cascade,
                               image_data BYTEA
);

create table seller_comment(
                               id int generated by default as identity primary key,
                               seller_id int references user_customer(id) on delete cascade,
                               created_date date,
                               fullname varchar,
                               comment text not null,
                               rate int check ( rate > 0 and rate < 6)
);